CREATE TABLE `ad_performance` (
	`ad_id` varchar(128) NOT NULL,
	`date` date NOT NULL,
	`publisher_platform` varchar(64) NOT NULL DEFAULT 'unknown',
	`account_id` varchar(64),
	`account_name` text,
	`campaign_id` varchar(128),
	`campaign_name` text,
	`adset_id` varchar(128),
	`adset_name` text,
	`ad_name` text,
	`creative_id` varchar(128),
	`ad_type` varchar(32),
	`content_fingerprint` varchar(24),
	`image_hash` varchar(128),
	`video_id` varchar(128),
	`impressions` int NOT NULL DEFAULT 0,
	`reach` int,
	`frequency` decimal(8,4),
	`spend` decimal(12,4) NOT NULL DEFAULT '0',
	`cpm` decimal(10,4),
	`clicks` int,
	`ctr` decimal(10,6),
	`link_ctr` decimal(10,6),
	`cpc` decimal(10,4),
	`cpc_link` decimal(10,4),
	`link_clicks` int,
	`landing_page_views` int,
	`cost_per_lpv` decimal(10,4),
	`results` decimal(12,4),
	`cost_per_result` decimal(12,4),
	`conv_event` text,
	`optimization_goal` varchar(128),
	`page_likes` int,
	`cost_per_page_like` decimal(10,4),
	`post_engagement` int,
	`cost_per_post_engagement` decimal(10,4),
	`page_engagement` int,
	`cost_per_page_engagement` decimal(10,4),
	`fb_leads` int,
	`cost_per_fb_lead` decimal(10,4),
	`video_views` int,
	`cost_per_video_view` decimal(10,4),
	`video_continuous_2s_views` int,
	`cost_per_2s_view` decimal(10,4),
	`thruplays` int,
	`cost_per_thruplay` decimal(10,4),
	`video_avg_watch_time` decimal(10,4),
	`video_views_25` int,
	`video_views_50` int,
	`video_views_75` int,
	`video_views_95` int,
	`video_views_100` int,
	`estimated_ad_recallers` int,
	`cost_per_recaller` decimal(10,4),
	`estimated_ad_recall_rate` decimal(10,6),
	`synced_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ad_performance_ad_id_date_publisher_platform_pk` PRIMARY KEY(`ad_id`,`date`,`publisher_platform`)
);
--> statement-breakpoint
CREATE TABLE `ad_source_details` (
	`creative_id` varchar(128) NOT NULL,
	`account_id` varchar(64),
	`campaign_id` varchar(128),
	`ad_id` varchar(128),
	`ad_name` text,
	`media_type` varchar(32),
	`image_url` text,
	`image_hash` varchar(128),
	`video_id` varchar(128),
	`content_fingerprint` varchar(24),
	`destination_url` text,
	`primary_text` text,
	`headline` text,
	`description` text,
	`cta_type` varchar(64),
	`source_payload` json,
	`last_seen_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ad_source_details_creative_id` PRIMARY KEY(`creative_id`)
);
--> statement-breakpoint
CREATE TABLE `creative_fatigue_results` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`analysis_run_id` varchar(64) NOT NULL,
	`analyzed_at` timestamp NOT NULL DEFAULT (now()),
	`account_id` varchar(64),
	`date_from` date NOT NULL,
	`date_to` date NOT NULL,
	`content_fingerprint` varchar(128),
	`creative_ids` json DEFAULT ('[]'),
	`ad_names` json DEFAULT ('[]'),
	`representative_name` text,
	`campaign_ids` json DEFAULT ('[]'),
	`campaign_name` text,
	`optimization_goal` varchar(128),
	`media_type` varchar(32),
	`eligible` boolean NOT NULL DEFAULT false,
	`total_spend` decimal(14,4),
	`total_impressions` bigint,
	`total_events` decimal(14,4),
	`days_active` int,
	`avg_ctr` decimal(10,6),
	`avg_frequency` decimal(8,4),
	`early_ctr` decimal(10,6),
	`recent_ctr` decimal(10,6),
	`ctr_drop` decimal(8,6),
	`early_spend` decimal(14,4),
	`recent_spend` decimal(14,4),
	`early_events` decimal(14,4),
	`recent_events` decimal(14,4),
	`early_cpe` decimal(12,4),
	`recent_cpe` decimal(12,4),
	`cpe_degrade` decimal(8,6),
	`ewma_early` decimal(10,6),
	`ewma_late` decimal(10,6),
	`ewma_drop` decimal(8,6),
	`frequency_fatigue` decimal(6,4),
	`reliability` decimal(6,4),
	`cpe_weight` decimal(4,2),
	`ctr_weight` decimal(4,2),
	`ewma_weight` decimal(4,2),
	`freq_weight` decimal(4,2),
	`raw_signal` decimal(8,6),
	`fatigue_score` decimal(6,2),
	`fatigue_label` varchar(64),
	`fatigue_status` enum('URGENT','REFRESH','MONITOR','HEALTHY','IMPROVING','BLOCKED'),
	`badge_cpe_cdr` boolean NOT NULL DEFAULT false,
	`badge_ctr_split` boolean NOT NULL DEFAULT false,
	`badge_ewma` boolean NOT NULL DEFAULT false,
	`badge_frequency` boolean NOT NULL DEFAULT false,
	`notification_sent` boolean NOT NULL DEFAULT false,
	`notification_level` enum('emerging','possible','probable'),
	CONSTRAINT `creative_fatigue_results_id` PRIMARY KEY(`id`),
	CONSTRAINT `cfr_run_fingerprint_unique` UNIQUE(`analysis_run_id`,`content_fingerprint`)
);
--> statement-breakpoint
CREATE TABLE `meta_sync_history` (
	`id` bigint AUTO_INCREMENT NOT NULL,
	`mode` enum('manual','scheduled','csv','breakdown') NOT NULL,
	`account_id` varchar(64),
	`campaign_filter` text,
	`date_from` date,
	`date_to` date,
	`rows_upserted` int NOT NULL DEFAULT 0,
	`ads_processed` int NOT NULL DEFAULT 0,
	`adsets_processed` int NOT NULL DEFAULT 0,
	`duration_ms` int NOT NULL DEFAULT 0,
	`status` enum('success','partial','error') NOT NULL,
	`error_message` text,
	`warnings` json DEFAULT ('[]'),
	`created_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `meta_sync_history_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `meta_sync_schedule` (
	`id` int NOT NULL DEFAULT 1,
	`enabled` boolean NOT NULL DEFAULT false,
	`utc_hour` int NOT NULL DEFAULT 6,
	`rolling_days` int NOT NULL DEFAULT 14,
	`vault_token_id` int,
	`account_id` varchar(64) NOT NULL DEFAULT '',
	`campaign_ids` text,
	`target_table` varchar(64) NOT NULL DEFAULT 'ad_performance',
	`last_run_at` timestamp,
	`last_run_status` enum('success','partial','error'),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `meta_sync_schedule_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE INDEX `ap_fingerprint_date_idx` ON `ad_performance` (`content_fingerprint`,`date`);--> statement-breakpoint
CREATE INDEX `ap_creative_id_date_idx` ON `ad_performance` (`creative_id`,`date`);--> statement-breakpoint
CREATE INDEX `ap_campaign_id_date_idx` ON `ad_performance` (`campaign_id`,`date`);--> statement-breakpoint
CREATE INDEX `ap_image_hash_fp_idx` ON `ad_performance` (`image_hash`);--> statement-breakpoint
CREATE INDEX `ap_video_id_fp_idx` ON `ad_performance` (`video_id`);--> statement-breakpoint
CREATE INDEX `ap_synced_at_idx` ON `ad_performance` (`synced_at`);--> statement-breakpoint
CREATE INDEX `asd_image_hash_fp_idx` ON `ad_source_details` (`image_hash`);--> statement-breakpoint
CREATE INDEX `asd_video_id_fp_idx` ON `ad_source_details` (`video_id`);--> statement-breakpoint
CREATE INDEX `cfr_run_score_idx` ON `creative_fatigue_results` (`analysis_run_id`,`fatigue_score`);--> statement-breakpoint
CREATE INDEX `cfr_fingerprint_run_idx` ON `creative_fatigue_results` (`content_fingerprint`,`analyzed_at`);--> statement-breakpoint
CREATE INDEX `cfr_notification_idx` ON `creative_fatigue_results` (`notification_sent`,`notification_level`);--> statement-breakpoint
CREATE INDEX `meta_sync_history_created_at_idx` ON `meta_sync_history` (`created_at`);